name: Reusable Brand Deployment

on:
  workflow_call:
    inputs:
      target_environment:
        description: 'The deployment target environment (dev, staging, main)'
        required: true
        type: string
      deploy_translations:
        description: 'Set to true to also deploy translations for the brand'
        required: false
        type: boolean
        default: false 

jobs:
  deploy_brands:
    environment: ${{ inputs.target_environment }}
    
    strategy:
          matrix:
            brand: ['BRAND_A', 'BRAND_B', 'BRAND_C', 'BRAND_D']
        
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Deploy Brand ${{ matrix.brand }} to ${{ inputs.target_environment }}
        id: main_deploy
        run: |
          echo ${{ format('{0}_BASE_URL', matrix.brand) }}"
          echo ${{ format('{0}_API_KEY', matrix.brand) }}"
          echo "Initiating core deployment for ${{ matrix.brand }}..."
        env:
          BRAND_NAME: ${{ matrix.brand }}
          DEPLOY_ENV: ${{ inputs.target_environment }}
          
      - name: Deploy Translations for ${{ matrix.brand }}
        if: ${{ inputs.deploy_translations }}
        run: |
          echo "Deploying translations for ${{ matrix.brand }}..."
